version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
    deploy:
      mode: replicated
      replicas: 1
      update_config:
          parallelism: 1
          order: start-first  
    networks:
      main:
        aliases:
          - jaeger
networks:
  main:
    external: true
