version: "3.8"

services:
  mysql:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 15s
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      main:
        aliases:
          - mysql
networks:
  main:
    external: true